//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebasSistemaFOP.ServicioCatalogos {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/ServiciosFOP")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioCatalogos.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        PruebasSistemaFOP.ServicioCatalogos.CompositeType GetDataUsingDataContract(PruebasSistemaFOP.ServicioCatalogos.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<PruebasSistemaFOP.ServicioCatalogos.CompositeType> GetDataUsingDataContractAsync(PruebasSistemaFOP.ServicioCatalogos.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : PruebasSistemaFOP.ServicioCatalogos.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<PruebasSistemaFOP.ServicioCatalogos.IService1>, PruebasSistemaFOP.ServicioCatalogos.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public PruebasSistemaFOP.ServicioCatalogos.CompositeType GetDataUsingDataContract(PruebasSistemaFOP.ServicioCatalogos.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<PruebasSistemaFOP.ServicioCatalogos.CompositeType> GetDataUsingDataContractAsync(PruebasSistemaFOP.ServicioCatalogos.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioCatalogos.IServicioCatalogos")]
    public interface IServicioCatalogos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCatalogos/ObtenerCampanas", ReplyAction="http://tempuri.org/IServicioCatalogos/ObtenerCampanasResponse")]
        System.Collections.Generic.KeyValuePair<int, string>[] ObtenerCampanas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCatalogos/ObtenerCampanas", ReplyAction="http://tempuri.org/IServicioCatalogos/ObtenerCampanasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.KeyValuePair<int, string>[]> ObtenerCampanasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCatalogos/ObtenerTurnos", ReplyAction="http://tempuri.org/IServicioCatalogos/ObtenerTurnosResponse")]
        System.Collections.Generic.KeyValuePair<int, string>[] ObtenerTurnos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCatalogos/ObtenerTurnos", ReplyAction="http://tempuri.org/IServicioCatalogos/ObtenerTurnosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.KeyValuePair<int, string>[]> ObtenerTurnosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioCatalogosChannel : PruebasSistemaFOP.ServicioCatalogos.IServicioCatalogos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioCatalogosClient : System.ServiceModel.ClientBase<PruebasSistemaFOP.ServicioCatalogos.IServicioCatalogos>, PruebasSistemaFOP.ServicioCatalogos.IServicioCatalogos {
        
        public ServicioCatalogosClient() {
        }
        
        public ServicioCatalogosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioCatalogosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCatalogosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCatalogosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.KeyValuePair<int, string>[] ObtenerCampanas() {
            return base.Channel.ObtenerCampanas();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.KeyValuePair<int, string>[]> ObtenerCampanasAsync() {
            return base.Channel.ObtenerCampanasAsync();
        }
        
        public System.Collections.Generic.KeyValuePair<int, string>[] ObtenerTurnos() {
            return base.Channel.ObtenerTurnos();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.KeyValuePair<int, string>[]> ObtenerTurnosAsync() {
            return base.Channel.ObtenerTurnosAsync();
        }
    }
}
